---
title: "Sayote Price Forecasting"
author: "Gretchen Ollani"
format: html
editor: visual
---

## BACKGROUND

```{r}
library(forecast)
library(ggplot2)
library(readr)
library(zoo)# load the forecast packages
library(forecast)
# load the ggplot2 packages
library(ggplot2)
# load the readr packages
library(readr)
# load the zoo package
library(zoo)
```

```{r}
sayote_ <- read_csv("/cloud/project/CSV/sayote.csv", col_types = cols(Week = col_date(format = "%Y-%m-%d")))
sayote_ts <- ts(sayote_[,2], freq=365.25/7, start=2017+295/365.25)
sayote_ts %>%
  autoplot()
```

```{r}
sayote_decomp <- decompose(na.locf(sayote_ts), type="additive")
autoplot(sayote_decomp)
```

```{r}
training_s <- subset(sayote_ts, end=length(sayote_ts)-8)
test_sayote_ts <- subset(sayote_ts, start=length(sayote_ts)-8)
fc_training_sayote<-forecast(training_s)
fc_training_sayote %>%
  forecast(h=60) %>%
  autoplot() +autolayer(test_sayote_ts)
```

```{r}
fc_training_sayote
```

```{r}
fc_sayote<-forecast(sayote_ts)
fc_sayote %>%
  forecast(h=27) %>%
  autoplot()
```

```{r}
tail(sayote_)
min(sayote_ts)
max(sayote_ts)
which.min(sayote_ts)
```

```{r}
bestfit_sayote <- list(aicc=Inf)
for(i in 1:25)
{
  fit_sayote <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=i), seasonal=FALSE)
  if(fit_sayote$aicc < bestfit_sayote$aicc)
    bestfit_sayote <- fit_sayote
  else break;
}
```

```{r}

summary(bestfit_sayote)
```

```{r}
fc_arima_sayote <- forecast(bestfit_sayote, xreg=fourier(sayote_ts, K=1, h=26))
plot(fc_arima_sayote)
```

```{r}
fc_arima_sayote
```

```{r}
fit_sayote_ts1 <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=1), seasonal=FALSE)
fit_sayote_ts2 <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=2), seasonal=FALSE)
fit_sayote_ts3 <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=3), seasonal=FALSE)
fit_sayote_ts4 <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=4), seasonal=FALSE)
fit_sayote_ts5 <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=5), seasonal=FALSE)
fit_sayote_ts6 <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=6), seasonal=FALSE)
fit_sayote_ts7 <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=7), seasonal=FALSE)
fit_sayote_ts8 <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=8), seasonal=FALSE)
fit_sayote_ts9 <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=9), seasonal=FALSE)
fit_sayote_ts10 <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=10), seasonal=FALSE)
fit_sayote_ts11 <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=11), seasonal=FALSE)
fit_sayote_ts12 <- auto.arima(sayote_ts, xreg=fourier(sayote_ts, K=12), seasonal=FALSE)
```

```{r}
aics<-c(AIC(fit_sayote_ts1),AIC(fit_sayote_ts2),AIC(fit_sayote_ts3),AIC(fit_sayote_ts4),AIC(fit_sayote_ts5),AIC(fit_sayote_ts6),AIC(fit_sayote_ts7),AIC(fit_sayote_ts8),AIC(fit_sayote_ts9),AIC(fit_sayote_ts10),AIC(fit_sayote_ts11),AIC(fit_sayote_ts12))
plot(aics)
```

```{r}
fc_sayote_ts1 <- forecast(fit_sayote_ts1, xreg=fourier(sayote_ts, K=1, h=26))
plot(fc_sayote_ts1)
```

```{r}
fc_sayote_ts1
```

```{r}
accuracy(fc_sayote_ts1)
```

```{r}
accuracy(fc_arima_sayote)
```

```{r}
accuracy(fc_sayote_ts1)
```
