---
title: "Squash(Suprema) Price Forecasting"
author: "Aepril Jean Binwag"
format: html
editor: visual
---

## BACKGROUND

```{r}
library(forecast)
library(ggplot2)
library(readr)
library (zoo)
```

```{r}
squash_suprema <- read_csv("/Users/acer/Documents/R projects/Sec math 17/NVAT-Price-Forecasting/CSV/squash-suprema.csv", col_types = cols(Week = col_date(format = "%Y-%m-%d")))
squash_suprema_ts<- ts(squash_suprema[,2], freq=365.25/7, start=2017+302/365.25)
squash_suprema_ts %>%
  autoplot()
```

```{r}
ss_decomp <- decompose(na.locf(squash_suprema_ts), type="additive")
autoplot(squash_suprema_ts)
```

```{r}
training_ss <- subset(squash_suprema_ts, end=length(squash_suprema_ts)-8)
test_ss <- subset(squash_suprema_ts, start=length(squash_suprema_ts)-8)
fc_training_ss <- forecast(training_ss)
fc_training_ss %>%
  forecast(h=10) %>%
  autoplot() +autolayer(test_ss)
```

``` {_decomp)}
```

```{r}
fc_training_ss
```

```{r}
fc_ss<-forecast(squash_suprema_ts)
fc_ss %>%
  forecast(h=100) %>%
  autoplot()
```

```{r}
tail(squash_suprema_ts)
min(squash_suprema_ts)
max(squash_suprema_ts)
which.min(squash_suprema_ts)
```

```{r}
bestfit_ss <- list(aicc=Inf)
for(i in 1:25)
{
  fit_ss <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=i), seasonal=FALSE)
  if(fit_ss$aicc < bestfit_ss$aicc)
    bestfit_ss <- fit_ss
  else break;
} 
```

``` {K="i)," seasonal="FALSE)"}
  if(fit_ss$aicc < bestfit_ss$aicc)
    bestfit_ss <- fit_ss
  else break;
}
```

``` {)}
```

```{r}
summary(bestfit_ss)
```

```{r}
summary(bestfit_ss)
```

```{r}
fc_arima_ss <- forecast(bestfit_ss, xreg=fourier(squash_suprema_ts, K=1, h=26))
plot(fc_arima_ss)
```

```{r}
fc_arima_ss
```

```{r}
fit_ss1 <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=1), seasonal=FALSE)
fit_ss2 <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=2), seasonal=FALSE)
fit_ss3 <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=3), seasonal=FALSE)
fit_ss4 <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=4), seasonal=FALSE)
fit_ss5 <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=5), seasonal=FALSE)
fit_ss6 <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=6), seasonal=FALSE)
fit_ss7 <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=7), seasonal=FALSE)
fit_ss8 <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=8), seasonal=FALSE)
fit_ss9 <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=9), seasonal=FALSE)
fit_ss10 <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=10), seasonal=FALSE)
fit_ss11 <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=11), seasonal=FALSE)
fit_ss12 <- auto.arima(squash_suprema_ts, xreg=fourier(squash_suprema_ts, K=12), seasonal=FALSE)
```

```{r}
aics<-c(AIC(fit_ss1),AIC(fit_ss2),AIC(fit_ss3),AIC(fit_ss4),AIC(fit_ss5),AIC(fit_ss6),AIC(fit_ss7),AIC(fit_ss8),AIC(fit_ss9),AIC(fit_ss10),AIC(fit_ss11),AIC(fit_ss12))
plot(aics)
```

```{r}
fc_arima_man_ss <- forecast(fit_ss1, xreg=fourier(squash_suprema_ts, K=1, h=26))
plot(fc_arima_man_ss)
```

```{r}
fc_arima_man_ss
```

```{r}
accuracy(fc_ss)
```

```{r}
accuracy(fc_arima_man_ss)
```

\`\`\`
