---
title: "tomato avatar prices forceasting"
author: "Romilyn C. Aglipay"
format: html
editor: visual
---

## BACKGROUND

```{r}
library(forecast)
library(ggplot2)
library(readr)
library(zoo)
```

```{r}
tomato_avatar <- read_csv("/Users/ROMILYN AGLIPAY/OneDrive - Nueva Vizcaya State University/Documents/R PROJECT/SEC MATH 17/NVAT-Price-Forecasting/CSV/tomato-avatar.csv", col_types = cols(Week = col_date(format = "%Y-%m-%d")))
tomato_avatar_ts <- ts(tomato_avatar[,2], freq=365.25/7, start=2017+302/365.25)
tomato_avatar_ts  %>%
  autoplot()
```

```{r}
ta_decomp <- decompose(na.locf(tomato_avatar_ts), type="additive")
autoplot(ta_decomp)
```

```{r}
training_ta <- subset(tomato_avatar_ts, end=length(tomato_avatar_ts)-8)
test_ta <- subset(tomato_avatar_ts, start=length(tomato_avatar_ts)-8)
fc_training_ta <- forecast(training_ta)
fc_training_ta %>%
  forecast(h=10) %>%
  autoplot() +autolayer(test_ta)
```

```{r}
fc_training_ta
```

```{r}
fc_ta<-forecast(tomato_avatar_ts)
fc_ta %>%
  forecast(h=100) %>%
  autoplot()
```

```{r}
fc_ta
```

```{r}
tail(tomato_avatar)
min(tomato_avatar_ts)
max(tomato_avatar_ts)
which.min(tomato_avatar_ts)
```

```{r}
bestfit_ta <- list(aicc=Inf)
for(i in 1:25)
{
  fit_ta <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=i), seasonal=FALSE)
  if(fit_ta$aicc < bestfit_ta$aicc)
    bestfit_ta <- fit_ta
  else break;
}
```

```{r}
summary(bestfit_ta)
```

```{r}
fc_arima_ta <- forecast(bestfit_ta, xreg=fourier(tomato_avatar_ts, K=1, h=26))
plot(fc_arima_ta)
```

```{r}
fc_arima_ta
```

```{r}
fit_ta1 <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=1), seasonal=FALSE)
fit_ta2 <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=2), seasonal=FALSE)
fit_ta3 <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=3), seasonal=FALSE)
fit_ta4 <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=4), seasonal=FALSE)
fit_ta5 <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=5), seasonal=FALSE)
fit_ta6 <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=6), seasonal=FALSE)
fit_ta7 <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=7), seasonal=FALSE)
fit_ta8 <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=8), seasonal=FALSE)
fit_ta9 <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=9), seasonal=FALSE)
fit_ta10 <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=10), seasonal=FALSE)
fit_ta11 <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=11), seasonal=FALSE)
fit_ta12 <- auto.arima(tomato_avatar_ts, xreg=fourier(tomato_avatar_ts, K=12), seasonal=FALSE)
```

```{r}
aics<-c(AIC(fit_ta1),AIC(fit_ta2),AIC(fit_ta3),AIC(fit_ta4),AIC(fit_ta5),AIC(fit_ta6),AIC(fit_ta7),AIC(fit_ta8),AIC(fit_ta9),AIC(fit_ta10),AIC(fit_ta11),AIC(fit_ta12))
plot(aics)
```

```{r}
fc_arima_man_ta <- forecast(fit_ta1, xreg=fourier(tomato_avatar_ts, K=1, h=26))
plot(fc_arima_man_ta)
```

```{r}
fc_arima_man_ta
```

```{r}
accuracy(fc_ta)
```

```{r}
accuracy(fc_ta)
```
